// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.vaadin.event.Action;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.concurrent.TimeUnit;
public class Addquestion {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "/Users/clara/Desktop/Software Design/filesWeNeed/chromedriver");
		driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addquestion() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1200, 769));
	
    driver.findElement(By.id("gwt-uid-3")).sendKeys("nikola");
    driver.findElement(By.id("gwt-uid-5")).sendKeys("1234");
    driver.findElement(By.cssSelector(".v-slot:nth-child(1) > .v-button")).click();
    {
        WebElement element = driver.findElement(By.cssSelector(".v-grid-row:nth-child(2) > .v-grid-cell"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).clickAndHold().perform();
      }
      {
        WebElement element = driver.findElement(By.cssSelector(".v-grid-row:nth-child(2) > .v-grid-cell"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
      {
        WebElement element = driver.findElement(By.cssSelector(".v-grid-row:nth-child(2) > .v-grid-cell"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).release().perform();
      }
      driver.findElement(By.cssSelector(".v-grid-row:nth-child(2) > .v-grid-cell")).click();
      driver.findElement(By.cssSelector(".primary")).click();
      driver.findElement(By.id("gwt-uid-7")).sendKeys("new selenium test");
      driver.findElement(By.id("gwt-uid-9")).sendKeys("4");
      {
        WebElement dropdown = driver.findElement(By.cssSelector("#gwt-uid-11 > .v-select-select"));
        dropdown.findElement(By.xpath("//option[. = 'MediumEasy']")).click();
      }
      {
        WebElement element = driver.findElement(By.id("gwt-uid-13"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).clickAndHold().perform();
      }
      {
        WebElement element = driver.findElement(By.id("gwt-uid-13"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
      {
        WebElement element = driver.findElement(By.id("gwt-uid-13"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).release().perform();
      }
      driver.findElement(By.id("gwt-uid-13")).click();
      driver.findElement(By.id("gwt-uid-13")).sendKeys("6");
      driver.findElement(By.id("gwt-uid-15")).click();
      driver.findElement(By.id("gwt-uid-15")).sendKeys("Answer");
      driver.findElement(By.cssSelector("#gwt-uid-17 > .v-select-select")).click();
      {
        WebElement dropdown = driver.findElement(By.cssSelector("#gwt-uid-17 > .v-select-select"));
        dropdown.findElement(By.xpath("//option[. = 'StandardQuestion']")).click();
      }
      driver.findElement(By.cssSelector(".primary")).click();
    }
}
