//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.junit.Assert;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.vaadin.event.Action;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class createCourseTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	@Before
	public void setUp() {
		System.setProperty("webdriver.gecko.driver", "C:\\geckodriver.exe");
		driver = new FirefoxDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		driver.get("http://localhost:8080/");
		driver.manage().window().maximize();
		WebDriverWait wait = new WebDriverWait(driver, 100);
		wait.until(ExpectedConditions.elementToBeClickable(By.id("gwt-uid-3")));
		driver.findElement(By.id("gwt-uid-3")).sendKeys("JohnDoe");
		driver.findElement(By.id("gwt-uid-5")).sendKeys("enter");
		driver.findElement(By.cssSelector(".v-slot:nth-child(1) > .v-button")).click();
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void createExistingCourse() {
		new WebDriverWait(driver, 20).until(ExpectedConditions.urlToBe("http://localhost:8080/#!home"));
		driver.findElement(By.cssSelector(".v-textfield")).click();
		driver.findElement(By.cssSelector(".v-textfield")).sendKeys("Coms1002");
		driver.findElement(By.cssSelector(".v-button")).click();
		WebDriverWait wait = new WebDriverWait(driver, 3);
		wait.until(ExpectedConditions.textToBe(By.cssSelector(".v-label"),"Cannot add an existing course"));
	}

	@Test
	public void createEmptyCourse() {
		new WebDriverWait(driver, 20).until(ExpectedConditions.urlToBe("http://localhost:8080/#!home"));
		driver.findElement(By.cssSelector(".v-textfield")).click();
		driver.findElement(By.cssSelector(".v-button")).click();
		WebDriverWait wait = new WebDriverWait(driver, 3);
		wait.until(ExpectedConditions.textToBe(By.cssSelector(".v-label"),"Cannot add an empty course"));	
	}

	@Test
	public void createNewCourse() {
		new WebDriverWait(driver, 20).until(ExpectedConditions.urlToBe("http://localhost:8080/#!home"));
		driver.findElement(By.cssSelector(".v-textfield")).click();
		driver.findElement(By.cssSelector(".v-textfield")).sendKeys("Testt");//change this for new course
		driver.findElement(By.cssSelector(".v-button")).click();
		WebDriverWait wait = new WebDriverWait(driver, 3);
		wait.until(ExpectedConditions.textToBe(By.cssSelector(".v-label"),"Course added"));
	}
	@Test
	public void selectCourse() {
		new WebDriverWait(driver, 20).until(ExpectedConditions.urlToBe("http://localhost:8080/#!home"));
		driver.findElement(By.cssSelector(".v-grid-row:nth-child(4) > .v-grid-cell")).click();
		Assert.assertTrue("Question didn't load",new WebDriverWait(driver, 20).until(ExpectedConditions.urlToBe("http://localhost:8080/#!questionGrid")));	
	}

}

