--- 
deploy: 
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  true: 
    tags: true

jdk: oraclejdk8
language: java
script: "mvn clean verify"
